apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
 labels:
  type: webf
  app: frontend
spec:
 selector:
   matchLabels:
    type: webf
    app: frontend
 replicas: 1
 template:
   metadata:
     labels:
      type: webf
      app: frontend
      version: v10
   spec:
    containers:
    - name: frontend
      image: shtnfo/frontend:latest
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m