apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
spec:
 selector:
   matchLabels:
    type: web
    app: frontend
    version: v16
 replicas: 1
 template:
   metadata:
     labels:
       type: web
       app: frontend
       version: v16
   spec:
    containers:
    - name: frontend
      image: shtnfo/frontend:latest
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m